[package]
name = "playground"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rayon = "1.7.0"
rust_libs = {path = "../rust_libs"}

[dependencies.serde]
version = "1.0.85"
features = ["derive"]
